import json
from typing import Any
from unittest import mock

import httpx
from httpx import codes

import pytest
from pytest_httpx import HTTPXMock

from museflow.domain.entities.auth import OAuthProviderUserToken
from museflow.domain.entities.user import User
from museflow.domain.exceptions import ProviderNoActiveDeviceException
from museflow.domain.exceptions import ProviderPremiumRequiredException
from museflow.domain.types import PlaylistType
from museflow.infrastructure.adapters.providers.spotify.library import SpotifyLibraryAdapter
from museflow.infrastructure.adapters.providers.spotify.library import SpotifyLibraryFactory
from museflow.infrastructure.adapters.providers.spotify.oauth import SpotifyOAuthAdapter
from museflow.infrastructure.adapters.providers.spotify.types import SPOTIFY_PLAYLIST_ITEMS_LIMIT

from tests.unit.factories.entities.track import TrackFactory


class TestSpotifyLibraryFactory:
    @pytest.fixture
    def spotify_library_factory(
        self,
        mock_auth_token_repository: mock.AsyncMock,
        mock_provider_oauth: mock.AsyncMock,
    ) -> SpotifyLibraryFactory:
        return SpotifyLibraryFactory(
            auth_token_repository=mock_auth_token_repository,
            oauth_client=mock_provider_oauth,
        )

    def test_create__nominal(
        self,
        user: User,
        auth_token: OAuthProviderUserToken,
        spotify_library_factory: SpotifyLibraryFactory,
    ) -> None:
        spotify_library = spotify_library_factory.create(user, auth_token)
        assert isinstance(spotify_library, SpotifyLibraryAdapter)
        assert spotify_library.user == user
        assert spotify_library.session_client.auth_token == auth_token


class TestSpotifyLibrary:
    @pytest.fixture
    def playlist_id(self) -> str:
        return "5ta70oLZcXLReU7bEEXQXy"

    @pytest.fixture
    def playlist_created_response(self, playlist_id: str) -> dict[str, Any]:
        return {
            "collaborative": False,
            "description": "Auto-generated by museflow",
            "external_urls": {"spotify": f"https://open.spotify.com/playlist/{playlist_id}"},
            "followers": {"href": None, "total": 0},
            "href": f"https://api.spotify.com/v1/playlists/{playlist_id}",
            "id": playlist_id,
            "images": [],
            "primary_color": None,
            "name": "test",
            "type": "playlist",
            "uri": f"spotify:playlist:{playlist_id}",
            "owner": {
                "href": "https://api.spotify.com/v1/users/testuser",
                "id": "testuser",
                "type": "user",
                "uri": "spotify:user:testuser",
                "display_name": None,
                "external_urls": {"spotify": "https://open.spotify.com/user/testuser"},
            },
            "public": False,
            "snapshot_id": "AAABqHv3vKen0GXlNvOafjopK9+V3Cae",
            "tracks": {"limit": 100, "next": None, "offset": 0, "previous": None, "href": "", "total": 0, "items": []},
            "items": {"limit": 100, "next": None, "offset": 0, "previous": None, "href": "", "total": 0, "items": []},
        }

    async def test__no_active_device(
        self,
        spotify_library: SpotifyLibraryAdapter,
        spotify_oauth: SpotifyOAuthAdapter,
        httpx_mock: HTTPXMock,
    ) -> None:
        httpx_mock.add_response(
            url=f"{spotify_oauth.base_url}/me/player/play",
            method="PUT",
            status_code=codes.NOT_FOUND,
        )
        with pytest.raises(ProviderNoActiveDeviceException):
            await spotify_library.play_track("6rqhFgbbKwnb9MLmUQDhG6")

    async def test__premium_required(
        self,
        spotify_library: SpotifyLibraryAdapter,
        spotify_oauth: SpotifyOAuthAdapter,
        httpx_mock: HTTPXMock,
    ) -> None:
        httpx_mock.add_response(
            url=f"{spotify_oauth.base_url}/me/player/play",
            method="PUT",
            status_code=codes.FORBIDDEN,
        )
        with pytest.raises(ProviderPremiumRequiredException):
            await spotify_library.play_track("6rqhFgbbKwnb9MLmUQDhG6")

    async def test__unhandled_http_error__reraises(
        self,
        spotify_library: SpotifyLibraryAdapter,
        spotify_oauth: SpotifyOAuthAdapter,
        httpx_mock: HTTPXMock,
    ) -> None:
        httpx_mock.add_response(
            url=f"{spotify_oauth.base_url}/me/player/play",
            method="PUT",
            status_code=408,  # 4xx ≠ 429 → not retried by tenacity
        )
        with pytest.raises(httpx.HTTPStatusError):
            await spotify_library.play_track("6rqhFgbbKwnb9MLmUQDhG6")

    async def test__create_playlist__empty_tracks(
        self,
        spotify_library: SpotifyLibraryAdapter,
        spotify_oauth: SpotifyOAuthAdapter,
        httpx_mock: HTTPXMock,
        playlist_created_response: dict[str, Any],
    ) -> None:
        httpx_mock.add_response(
            url=f"{spotify_oauth.base_url}/me/playlists", method="POST", json=playlist_created_response
        )

        playlist = await spotify_library.create_playlist(name="test", type=PlaylistType.DISCOVERY, tracks=[])

        items_requests = [r for r in httpx_mock.get_requests() if "/items" in str(r.url)]
        assert len(items_requests) == 0
        assert playlist.tracks == []

    async def test__create_playlist__single_batch(
        self,
        spotify_library: SpotifyLibraryAdapter,
        spotify_oauth: SpotifyOAuthAdapter,
        httpx_mock: HTTPXMock,
        playlist_id: str,
        playlist_created_response: dict[str, Any],
    ) -> None:
        tracks = TrackFactory.batch(SPOTIFY_PLAYLIST_ITEMS_LIMIT - 1)
        httpx_mock.add_response(
            url=f"{spotify_oauth.base_url}/me/playlists", method="POST", json=playlist_created_response
        )
        httpx_mock.add_response(
            url=f"{spotify_oauth.base_url}/playlists/{playlist_id}/items",
            method="POST",
            json={"snapshot_id": "snap-only"},
        )

        playlist = await spotify_library.create_playlist(name="test", type=PlaylistType.DISCOVERY, tracks=tracks)

        items_requests = [r for r in httpx_mock.get_requests() if "/items" in str(r.url)]
        assert len(items_requests) == 1
        assert len(json.loads(items_requests[0].content)["uris"]) == SPOTIFY_PLAYLIST_ITEMS_LIMIT - 1
        assert playlist.snapshot_id == "snap-only"

    async def test__create_playlist__multiple_batches(
        self,
        spotify_library: SpotifyLibraryAdapter,
        spotify_oauth: SpotifyOAuthAdapter,
        httpx_mock: HTTPXMock,
        playlist_id: str,
        playlist_created_response: dict[str, Any],
    ) -> None:
        tracks = TrackFactory.batch(SPOTIFY_PLAYLIST_ITEMS_LIMIT + 1)
        httpx_mock.add_response(
            url=f"{spotify_oauth.base_url}/me/playlists", method="POST", json=playlist_created_response
        )
        httpx_mock.add_response(
            url=f"{spotify_oauth.base_url}/playlists/{playlist_id}/items",
            method="POST",
            json={"snapshot_id": "snap-first"},
        )
        httpx_mock.add_response(
            url=f"{spotify_oauth.base_url}/playlists/{playlist_id}/items",
            method="POST",
            json={"snapshot_id": "snap-last"},
        )

        playlist = await spotify_library.create_playlist(name="test", type=PlaylistType.DISCOVERY, tracks=tracks)

        items_requests = [r for r in httpx_mock.get_requests() if "/items" in str(r.url)]
        assert len(items_requests) == 2
        assert len(json.loads(items_requests[0].content)["uris"]) == SPOTIFY_PLAYLIST_ITEMS_LIMIT
        assert len(json.loads(items_requests[1].content)["uris"]) == 1
        assert playlist.snapshot_id == "snap-last"
