"""empty message

Revision ID: 04157855f63c
Revises: 19fd9c4de218
Create Date: 2026-06-03 14:38:33.190136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04157855f63c'
down_revision: Union[str, Sequence[str], None] = '19fd9c4de218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('museflow_discovery_playlist_track', sa.Column('track_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_museflow_discovery_playlist_track_fingerprint'), table_name='museflow_discovery_playlist_track')
    op.create_foreign_key(None, 'museflow_discovery_playlist_track', 'museflow_track', ['track_id'], ['id'], ondelete='CASCADE')
    op.drop_column('museflow_discovery_playlist_track', 'fingerprint')
    op.drop_column('museflow_discovery_playlist_track', 'score')
    op.drop_column('museflow_discovery_playlist_track', 'track_name')
    op.drop_column('museflow_discovery_playlist_track', 'provider')
    op.drop_column('museflow_discovery_playlist_track', 'updated_at')
    op.drop_column('museflow_discovery_playlist_track', 'provider_id')
    op.drop_column('museflow_discovery_playlist_track', 'artist_names')
    op.drop_column('museflow_discovery_playlist_track', 'created_at')
    op.add_column('museflow_track', sa.Column('source', sa.Integer(), nullable=False))
    op.add_column('museflow_track', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('museflow_track', 'score')
    op.drop_column('museflow_track', 'source')
    op.add_column('museflow_discovery_playlist_track', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('museflow_discovery_playlist_track', sa.Column('artist_names', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('museflow_discovery_playlist_track', sa.Column('provider_id', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.add_column('museflow_discovery_playlist_track', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('museflow_discovery_playlist_track', sa.Column('provider', postgresql.ENUM('SPOTIFY', name='musicprovider'), autoincrement=False, nullable=False))
    op.add_column('museflow_discovery_playlist_track', sa.Column('track_name', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.add_column('museflow_discovery_playlist_track', sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('museflow_discovery_playlist_track', sa.Column('fingerprint', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'museflow_discovery_playlist_track', type_='foreignkey')
    op.create_index(op.f('ix_museflow_discovery_playlist_track_fingerprint'), 'museflow_discovery_playlist_track', ['fingerprint'], unique=False)
    op.drop_column('museflow_discovery_playlist_track', 'track_id')
    # ### end Alembic commands ###
