"""empty message

Revision ID: 19fd9c4de218
Revises: 2fc0a194d8fe
Create Date: 2026-06-02 14:47:31.545261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19fd9c4de218'
down_revision: Union[str, Sequence[str], None] = '2fc0a194d8fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('museflow_discovery_playlist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('provider', postgresql.ENUM('SPOTIFY', name='musicprovider', create_type=False), nullable=False),
    sa.Column('provider_id', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('focus', sa.Enum('EXPANSION', 'ROOTS_REVIVAL', 'CULTURAL_BRIDGE', name='discoveryfocus'), nullable=False),
    sa.Column('genre', sa.String(length=255), nullable=True),
    sa.Column('mood', sa.String(length=255), nullable=True),
    sa.Column('custom_instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['museflow_taste_profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['museflow_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_museflow_discovery_playlist_user_id'), 'museflow_discovery_playlist', ['user_id'], unique=False)
    op.create_table('museflow_discovery_playlist_track',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('playlist_id', sa.UUID(), nullable=False),
    sa.Column('provider', postgresql.ENUM('SPOTIFY', name='musicprovider', create_type=False), nullable=False),
    sa.Column('provider_id', sa.String(length=512), nullable=False),
    sa.Column('track_name', sa.String(length=512), nullable=False),
    sa.Column('artist_names', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=512), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['museflow_discovery_playlist.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_museflow_discovery_playlist_track_fingerprint'), 'museflow_discovery_playlist_track', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_museflow_discovery_playlist_track_playlist_id'), 'museflow_discovery_playlist_track', ['playlist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_museflow_discovery_playlist_track_playlist_id'), table_name='museflow_discovery_playlist_track')
    op.drop_index(op.f('ix_museflow_discovery_playlist_track_fingerprint'), table_name='museflow_discovery_playlist_track')
    op.drop_table('museflow_discovery_playlist_track')
    op.drop_index(op.f('ix_museflow_discovery_playlist_user_id'), table_name='museflow_discovery_playlist')
    op.drop_table('museflow_discovery_playlist')
    # ### end Alembic commands ###
