"""empty message

Revision ID: 872c6c7e6317
Revises:
Create Date: 2026-03-20 12:51:22.540003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '872c6c7e6317'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('museflow_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_museflow_user_email'), 'museflow_user', ['email'], unique=True)
    op.create_table('museflow_artist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('sources', sa.Integer(), nullable=False),
    sa.Column('top_position', sa.Integer(), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('provider', sa.Enum('SPOTIFY', name='musicprovider'), nullable=False),
    sa.Column('provider_id', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['museflow_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider_id', name='uq_museflow_artist_user_provider_id')
    )
    op.create_index(op.f('ix_museflow_artist_user_id'), 'museflow_artist', ['user_id'], unique=False)
    op.create_index('ix_museflow_artist_user_provider', 'museflow_artist', ['user_id', 'provider'], unique=False)
    op.create_index('ix_museflow_artist_user_sources', 'museflow_artist', ['user_id', 'sources'], unique=False)
    op.create_table('museflow_auth_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('SPOTIFY', name='musicprovider'), nullable=False),
    sa.Column('state', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['museflow_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_provider_auth_state')
    )
    op.create_index(op.f('ix_museflow_auth_state_state'), 'museflow_auth_state', ['state'], unique=True)
    op.create_table('museflow_auth_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('SPOTIFY', name='musicprovider'), nullable=False),
    sa.Column('token_type', sa.String(length=512), nullable=False),
    sa.Column('token_access', sa.String(length=512), nullable=False),
    sa.Column('token_refresh', sa.String(length=512), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['museflow_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_provider_auth_token')
    )
    op.create_table('museflow_track',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('artists', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('album', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('isrc', sa.String(length=512), nullable=True),
    sa.Column('fingerprint', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('sources', sa.Integer(), nullable=False),
    sa.Column('top_position', sa.Integer(), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('provider', sa.Enum('SPOTIFY', name='musicprovider'), nullable=False),
    sa.Column('provider_id', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['museflow_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider_id', name='uq_museflow_track_user_provider_id')
    )
    op.create_index(op.f('ix_museflow_track_fingerprint'), 'museflow_track', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_museflow_track_isrc'), 'museflow_track', ['isrc'], unique=False)
    op.create_index('ix_museflow_track_user_fingerprint', 'museflow_track', ['user_id', 'fingerprint'], unique=False)
    op.create_index(op.f('ix_museflow_track_user_id'), 'museflow_track', ['user_id'], unique=False)
    op.create_index('ix_museflow_track_user_isrc', 'museflow_track', ['user_id', 'isrc'], unique=False)
    op.create_index('ix_museflow_track_user_provider', 'museflow_track', ['user_id', 'provider'], unique=False)
    op.create_index('ix_museflow_track_user_sources', 'museflow_track', ['user_id', 'sources'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_museflow_track_user_sources', table_name='museflow_track')
    op.drop_index('ix_museflow_track_user_provider', table_name='museflow_track')
    op.drop_index('ix_museflow_track_user_isrc', table_name='museflow_track')
    op.drop_index(op.f('ix_museflow_track_user_id'), table_name='museflow_track')
    op.drop_index('ix_museflow_track_user_fingerprint', table_name='museflow_track')
    op.drop_index(op.f('ix_museflow_track_isrc'), table_name='museflow_track')
    op.drop_index(op.f('ix_museflow_track_fingerprint'), table_name='museflow_track')
    op.drop_table('museflow_track')
    op.drop_table('museflow_auth_token')
    op.drop_index(op.f('ix_museflow_auth_state_state'), table_name='museflow_auth_state')
    op.drop_table('museflow_auth_state')
    op.drop_index('ix_museflow_artist_user_sources', table_name='museflow_artist')
    op.drop_index('ix_museflow_artist_user_provider', table_name='museflow_artist')
    op.drop_index(op.f('ix_museflow_artist_user_id'), table_name='museflow_artist')
    op.drop_table('museflow_artist')
    op.drop_index(op.f('ix_museflow_user_email'), table_name='museflow_user')
    op.drop_table('museflow_user')
    # ### end Alembic commands ###
