"""empty message

Revision ID: a9f5ecb0a7b5
Revises:
Create Date: 2026-02-22 14:55:42.056985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9f5ecb0a7b5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spotifagent_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spotifagent_user_email'), 'spotifagent_user', ['email'], unique=True)
    op.create_table('spotifagent_auth_provider_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('SPOTIFY', name='musicprovider'), nullable=False),
    sa.Column('state', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['spotifagent_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_provider_pending_auth')
    )
    op.create_index(op.f('ix_spotifagent_auth_provider_state_state'), 'spotifagent_auth_provider_state', ['state'], unique=True)
    op.create_table('spotifagent_music_artist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('is_saved', sa.Boolean(), nullable=False),
    sa.Column('is_top', sa.Boolean(), nullable=False),
    sa.Column('top_position', sa.Integer(), nullable=True),
    sa.Column('genres', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('provider', sa.Enum('SPOTIFY', name='musicprovider'), nullable=False),
    sa.Column('provider_id', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['spotifagent_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider_id', name='uq_spotifagent_music_artist_user_provider_id')
    )
    op.create_index(op.f('ix_spotifagent_music_artist_user_id'), 'spotifagent_music_artist', ['user_id'], unique=False)
    op.create_table('spotifagent_music_track',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('is_saved', sa.Boolean(), nullable=False),
    sa.Column('is_top', sa.Boolean(), nullable=False),
    sa.Column('top_position', sa.Integer(), nullable=True),
    sa.Column('artists', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider', sa.Enum('SPOTIFY', name='musicprovider'), nullable=False),
    sa.Column('provider_id', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['spotifagent_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider_id', name='uq_spotifagent_music_track_user_provider_id')
    )
    op.create_index(op.f('ix_spotifagent_music_track_user_id'), 'spotifagent_music_track', ['user_id'], unique=False)
    op.create_table('spotify_account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_type', sa.String(length=512), nullable=False),
    sa.Column('token_access', sa.String(length=512), nullable=False),
    sa.Column('token_refresh', sa.String(length=512), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['spotifagent_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spotify_account_user_id'), 'spotify_account', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spotify_account_user_id'), table_name='spotify_account')
    op.drop_table('spotify_account')
    op.drop_index(op.f('ix_spotifagent_music_track_user_id'), table_name='spotifagent_music_track')
    op.drop_table('spotifagent_music_track')
    op.drop_index(op.f('ix_spotifagent_music_artist_user_id'), table_name='spotifagent_music_artist')
    op.drop_table('spotifagent_music_artist')
    op.drop_index(op.f('ix_spotifagent_auth_provider_state_state'), table_name='spotifagent_auth_provider_state')
    op.drop_table('spotifagent_auth_provider_state')
    op.drop_index(op.f('ix_spotifagent_user_email'), table_name='spotifagent_user')
    op.drop_table('spotifagent_user')
    # ### end Alembic commands ###
