"""empty message

Revision ID: b74d2db001d0
Revises: ec727be9792c
Create Date: 2026-05-26 12:11:13.039859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b74d2db001d0'
down_revision: Union[str, Sequence[str], None] = 'ec727be9792c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('museflow_taste_profile', sa.Column('checkpoint_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('museflow_taste_profile', sa.Column('checkpoint_batch_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('museflow_taste_profile', 'checkpoint_batch_index')
    op.drop_column('museflow_taste_profile', 'checkpoint_profile')
    # ### end Alembic commands ###
