"""empty message

Revision ID: cf11a07693bf
Revises:
Create Date: 2026-02-25 15:22:12.490862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf11a07693bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('museflow_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_museflow_user_email'), 'museflow_user', ['email'], unique=True)
    op.create_table('museflow_artist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('is_saved', sa.Boolean(), nullable=False),
    sa.Column('is_top', sa.Boolean(), nullable=False),
    sa.Column('top_position', sa.Integer(), nullable=True),
    sa.Column('genres', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('provider', sa.Enum('SPOTIFY', name='musicprovider'), nullable=False),
    sa.Column('provider_id', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['museflow_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider_id', name='uq_museflow_artist_user_provider_id')
    )
    op.create_index(op.f('ix_museflow_artist_user_id'), 'museflow_artist', ['user_id'], unique=False)
    op.create_table('museflow_auth_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('SPOTIFY', name='musicprovider'), nullable=False),
    sa.Column('state', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['museflow_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_provider_auth_state')
    )
    op.create_index(op.f('ix_museflow_auth_state_state'), 'museflow_auth_state', ['state'], unique=True)
    op.create_table('museflow_auth_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('SPOTIFY', name='musicprovider'), nullable=False),
    sa.Column('token_type', sa.String(length=512), nullable=False),
    sa.Column('token_access', sa.String(length=512), nullable=False),
    sa.Column('token_refresh', sa.String(length=512), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['museflow_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_provider_auth_token')
    )
    op.create_table('museflow_track',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('is_saved', sa.Boolean(), nullable=False),
    sa.Column('is_top', sa.Boolean(), nullable=False),
    sa.Column('top_position', sa.Integer(), nullable=True),
    sa.Column('artists', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider', sa.Enum('SPOTIFY', name='musicprovider'), nullable=False),
    sa.Column('provider_id', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['museflow_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider_id', name='uq_museflow_track_user_provider_id')
    )
    op.create_index(op.f('ix_museflow_track_user_id'), 'museflow_track', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_museflow_track_user_id'), table_name='museflow_track')
    op.drop_table('museflow_track')
    op.drop_table('museflow_auth_token')
    op.drop_index(op.f('ix_museflow_auth_state_state'), table_name='museflow_auth_state')
    op.drop_table('museflow_auth_state')
    op.drop_index(op.f('ix_museflow_artist_user_id'), table_name='museflow_artist')
    op.drop_table('museflow_artist')
    op.drop_index(op.f('ix_museflow_user_email'), table_name='museflow_user')
    op.drop_table('museflow_user')
    # ### end Alembic commands ###
