"""add genres and moods to track

Revision ID: d8bdbf027318
Revises: 51656d7d295c
Create Date: 2026-06-27 20:32:19.072434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8bdbf027318'
down_revision: Union[str, Sequence[str], None] = '51656d7d295c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('museflow_track', sa.Column('genres', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('museflow_track', sa.Column('moods', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('museflow_track', 'moods')
    op.drop_column('museflow_track', 'genres')
    # ### end Alembic commands ###
