"""empty message

Revision ID: ec727be9792c
Revises: eccf2c7afc7b
Create Date: 2026-05-25 19:47:24.101980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec727be9792c'
down_revision: Union[str, Sequence[str], None] = 'eccf2c7afc7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('museflow_track', sa.Column('played_at_last', sa.DateTime(timezone=True), nullable=True))
    op.add_column('museflow_track', sa.Column('played_at_first', sa.DateTime(timezone=True), nullable=True))
    op.add_column('museflow_track', sa.Column('played_count', sa.Integer(), nullable=False))
    op.drop_column('museflow_track', 'played_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('museflow_track', sa.Column('played_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('museflow_track', 'played_count')
    op.drop_column('museflow_track', 'played_at_first')
    op.drop_column('museflow_track', 'played_at_last')
    # ### end Alembic commands ###
