name: "Local"
version: 0.0.1
models:
  - title: "Qwen 7B"
    provider: "ollama"
    model: "qwen2.5-coder:7b"
tabAutocompleteModel:
  title: "Autocomplete"
  provider: "ollama"
  model: "qwen2.5-coder:1.5b"
